// API Keys
const PEXELS_API_KEY =
  'XM1cPVOd285bkUsc2iiOKjhLg7oGjwvXQCIHjextLMBD0ByhUGN4tDQD';
const OPENWEATHER_API_KEY = 'a64d9def357accae801b18b33d7bbe22';

// Alternative weather service (free, no key needed)
const USE_ALTERNATIVE_WEATHER = false;

// Fallback videos if API fails
const fallbackVideos = [
  'https://cdn.pixabay.com/video/2019/04/05/21046-329127438_large.mp4',
  'https://cdn.pixabay.com/video/2020/10/15/52795-470667958_large.mp4',
  'https://cdn.pixabay.com/video/2021/01/23/63246-506279742_large.mp4',
  'https://cdn.pixabay.com/video/2020/04/19/36337-410653426_large.mp4',
  'https://cdn.pixabay.com/video/2016/08/19/4131-180607973_large.mp4',
  'https://cdn.pixabay.com/video/2023/06/14/167032-836252994_large.mp4',
  'https://cdn.pixabay.com/video/2022/03/11/110857-689035517_large.mp4',
];

// Inspirational quotes
const quotes = [
  '"The only way to do great work is to love what you do." - Steve Jobs',
  '"Innovation distinguishes between a leader and a follower." - Steve Jobs',
  '"Stay hungry. Stay foolish." - Steve Jobs',
  '"The future belongs to those who believe in the beauty of their dreams." - Eleanor Roosevelt',
  '"It is during our darkest moments that we must focus to see the light." - Aristotle',
  '"The best time to plant a tree was 20 years ago. The second best time is now." - Chinese Proverb',
  '"Your time is limited, don\'t waste it living someone else\'s life." - Steve Jobs',
  '"The only impossible journey is the one you never begin." - Tony Robbins',
  '"Success is not final, failure is not fatal: it is the courage to continue that counts." - Winston Churchill',
  '"The way to get started is to quit talking and begin doing." - Walt Disney',
  '"Believe you can and you\'re halfway there." - Theodore Roosevelt',
  '"The mind is everything. What you think you become." - Buddha',
  '"Life is 10% what happens to you and 90% how you react to it." - Charles R. Swindoll',
  '"Change your thoughts and you change your world." - Norman Vincent Peale',
  '"The only limit to our realization of tomorrow will be our doubts of today." - Franklin D. Roosevelt',
  '"Do what you can, with what you have, where you are." - Theodore Roosevelt',
  '"Act as if what you do makes a difference. It does." - William James',
  '"Success usually comes to those who are too busy to be looking for it." - Henry David Thoreau',
  '"Don\'t watch the clock; do what it does. Keep going." - Sam Levenson',
  '"The harder I work, the luckier I get." - Gary Player',
  '"Everything you\'ve ever wanted is on the other side of fear." - George Addair',
  '"Opportunities don\'t happen. You create them." - Chris Grosser',
  '"Don\'t be afraid to give up the good to go for the great." - John D. Rockefeller',
  '"I find that the harder I work, the more luck I seem to have." - Thomas Jefferson',
  '"Success is walking from failure to failure with no loss of enthusiasm." - Winston Churchill',
  '"If you are working on something that you really care about, you don\'t have to be pushed." - Steve Jobs',
  '"People who are crazy enough to think they can change the world, are the ones who do." - Rob Siltanen',
  '"Failure will never overtake me if my determination to succeed is strong enough." - Og Mandino',
  '"We may encounter many defeats but we must not be defeated." - Maya Angelou',
  '"Knowing is not enough; we must apply. Wishing is not enough; we must do." - Johann Wolfgang Von Goethe',
  '"Whether you think you can or you think you can\'t, you\'re right." - Henry Ford',
  '"The successful warrior is the average man, with laser-like focus." - Bruce Lee',
  '"Take up one idea. Make that one idea your life." - Swami Vivekananda',
  '"Do not wait to strike till the iron is hot; but make it hot by striking." - William Butler Yeats',
  '"Great minds discuss ideas; average minds discuss events; small minds discuss people." - Eleanor Roosevelt',
  '"I have not failed. I\'ve just found 10,000 ways that won\'t work." - Thomas Edison',
  '"A person who never made a mistake never tried anything new." - Albert Einstein',
  '"The person who says it cannot be done should not interrupt the person who is doing it." - Chinese Proverb',
  '"There are no secrets to success. It is the result of preparation, hard work, and learning from failure." - Colin Powell',
  '"The way to get started is to quit talking and begin doing." - Walt Disney',
  '"If you really look closely, most overnight successes took a long time." - Steve Jobs',
  '"The real test is not whether you avoid this failure, because you won\'t. It\'s whether you let it harden or shame you." - Barack Obama',
  '"It\'s fine to celebrate success but it is more important to heed the lessons of failure." - Bill Gates',
  '"If you are not willing to risk the usual, you will have to settle for the ordinary." - Jim Rohn',
  '"Stop chasing the money and start chasing the passion." - Tony Hsieh',
  '"All our dreams can come true if we have the courage to pursue them." - Walt Disney',
  '"If you want to achieve excellence, you can get there today." - Thomas J. Watson',
  '"Success is not how high you have climbed, but how you make a positive difference to the world." - Roy T. Bennett',
  '"If you don\'t value your time, neither will others." - Kim Garst',
  '"You miss 100% of the shots you don\'t take." - Wayne Gretzky',
  '"I alone cannot change the world, but I can cast a stone across the water to create many ripples." - Mother Teresa',
  '"What we think, we become." - Buddha',
  '"The best revenge is massive success." - Frank Sinatra',
  '"Do one thing every day that scares you." - Eleanor Roosevelt',
  '"The distance between insanity and genius is measured only by success." - Bruce Feirstein',
  '"Don\'t be distracted by criticism. Remember, the only taste of success some people get is to take a bite out of you." - Zig Ziglar',
  '"You can\'t use up creativity. The more you use, the more you have." - Maya Angelou',
  '"If you can dream it, you can do it." - Walt Disney',
  '"Do what you love and the money will follow." - Marsha Sinetar',
  '"A creative man is motivated by the desire to achieve, not by the desire to beat others." - Ayn Rand',
  '"Courage is resistance to fear, mastery of fear - not absence of fear." - Mark Twain',
  '"Only put off until tomorrow what you are willing to die having left undone." - Pablo Picasso',
  '"The ones who are crazy enough to think they can change the world are the ones that do." - Anonymous',
  '"Don\'t let yesterday take up too much of today." - Will Rogers',
  '"You learn more from failure than from success. Don\'t let it stop you. Failure builds character." - Unknown',
  '"If you are working on something exciting that you really care about, you don\'t have to be pushed." - Steve Jobs',
  '"It\'s not whether you get knocked down, it\'s whether you get up." - Vince Lombardi',
  '"Some people dream of success, while other people get up every morning and make it happen." - Wayne Huizenga',
  '"The only place where success comes before work is in the dictionary." - Vidal Sassoon',
  '"Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart." - Roy T. Bennett',
  '"The road to success and the road to failure are almost exactly the same." - Colin R. Davis',
  '"I failed my way to success." - Thomas Edison',
  '"A successful man is one who can lay a firm foundation with the bricks others have thrown at him." - David Brinkley',
  '"No one can make you feel inferior without your consent." - Eleanor Roosevelt',
  '"The whole secret of a successful life is to find out what is one\'s destiny to do." - Henry Ford',
  '"If you\'re not stubborn, you\'ll give up on experiments too soon." - Jeff Bezos',
  '"You only live once, but if you do it right, once is enough." - Mae West',
  '"Be yourself; everyone else is already taken." - Oscar Wilde',
  '"A room without books is like a body without a soul." - Marcus Tullius Cicero',
  '"In three words I can sum up everything I\'ve learned about life: it goes on." - Robert Frost',
  '"To live is the rarest thing in the world. Most people exist, that is all." - Oscar Wilde',
  '"Without music, life would be a mistake." - Friedrich Nietzsche',
  '"We accept the love we think we deserve." - Stephen Chbosky',
  '"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment." - Ralph Waldo Emerson',
  '"Imperfection is beauty, madness is genius and it\'s better to be absolutely ridiculous than absolutely boring." - Marilyn Monroe',
  '"There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle." - Albert Einstein',
  '"It does not do to dwell on dreams and forget to live." - J.K. Rowling',
  '"Good friends, good books, and a sleepy conscience: this is the ideal life." - Mark Twain',
  '"Life is what happens to us while we are making other plans." - Allen Saunders',
  '"The difference between winning and losing is most often not quitting." - Walt Disney',
  '"Logic will get you from A to Z; imagination will get you everywhere." - Albert Einstein',
  '"The two most important days in your life are the day you are born and the day you find out why." - Mark Twain',
  '"Whatever you are, be a good one." - Abraham Lincoln',
  '"Everything has beauty, but not everyone sees it." - Confucius',
  '"How wonderful it is that nobody need wait a single moment before starting to improve the world." - Anne Frank',
  '"Life is not measured by the number of breaths we take, but by the moments that take our breath away." - Maya Angelou',
  '"When one door of happiness closes, another opens." - Helen Keller',
  '"Everything you can imagine is real." - Pablo Picasso',
  '"Try to be a rainbow in someone\'s cloud." - Maya Angelou',
  '"You are never too old to set another goal or to dream a new dream." - C.S. Lewis',
  '"Life itself is the most wonderful fairy tale." - Hans Christian Andersen',
];

// Video search queries for variety
const videoQueries = [
  'nature',
  'ocean',
  'mountains',
  'forest',
  'sky',
  'clouds',
  'abstract',
  'technology',
  'space',
  'city',
  'rain',
  'waves',
  'northern lights',
  'stars',
  'sunset',
  'particles',
  'aerial',
];

// Weather icons mapping
const weatherIcons = {
  Clear: 'fas fa-sun',
  Clouds: 'fas fa-cloud',
  Rain: 'fas fa-cloud-rain',
  Drizzle: 'fas fa-cloud-rain',
  Thunderstorm: 'fas fa-bolt',
  Snow: 'fas fa-snowflake',
  Mist: 'fas fa-smog',
  Fog: 'fas fa-smog',
  Haze: 'fas fa-smog',
};
